SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `activity_instance_fuli` (
`FULI_ID`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '福利ID' ,
`INSTANCE_ID`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '活动实例ID' ,
`GROUP_ID`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '群组ID' ,
`WEIXIN_ID_SENDER`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '送出者微信ID' ,
`WEIXIN_ID`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '领券者微信ID' ,
`FULI_MONEY`  int(11) NOT NULL COMMENT '抵扣金额' ,
`FULI_MONEY_VIP`  int(11) NOT NULL DEFAULT 0 COMMENT '对VIP会员的抵扣金额' ,
`AWARD_MONEY`  int(11) NOT NULL COMMENT '普通用户消费后奖励给送券者的金额' ,
`AWARD_MONEY_VIP`  int(11) NOT NULL DEFAULT 0 COMMENT '会员消费后奖励给送券者的金额' ,
`FULI_DESC`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '描述' ,
`USED_FLAG`  int(11) NOT NULL DEFAULT 0 COMMENT '是否已用' ,
`FULI_SORT`  int(11) NOT NULL ,
UNIQUE INDEX `instance_fuli_unique` (`FULI_ID`, `WEIXIN_ID`) USING BTREE 
)
ENGINE=MyISAM
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
CHECKSUM=0
ROW_FORMAT=Dynamic
DELAY_KEY_WRITE=0
;

CREATE TABLE `activity_instance_fuli1` (
`INSTANCE_ID`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '活动实例ID' ,
`WEIXIN_ID`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '领券者微信ID' ,
`WEIXIN_ID_SENDER`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '送出者微信ID' ,
`FULI_MONEY`  int(11) NOT NULL COMMENT '抵扣金额' ,
`AWARD_MONEY`  int(11) NOT NULL COMMENT '消费后奖励给送券者的金额' ,
`FULI_DESC`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '描述' ,
`USED_FLAG`  int(11) NOT NULL DEFAULT 0 COMMENT '是否已用' 
)
ENGINE=MyISAM
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
CHECKSUM=0
ROW_FORMAT=Dynamic
DELAY_KEY_WRITE=0
;

ALTER TABLE `activity_instance_signup` ADD COLUMN `SIGNUP_FULI`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '报名时的福利设置' AFTER `SIGNUP_ZHONGCHOU`;

ALTER TABLE `activity_instance_signup` ADD COLUMN `SIGNUP_FULI_MONEY`  int(11) NULL DEFAULT 0 COMMENT '代金券抵扣金额' AFTER `SIGNUP_FULI`;

ALTER TABLE `activity_instance_signup` ADD COLUMN `SIGNUP_FULI_AWARD_MONEY`  int(11) NULL DEFAULT 0 COMMENT '奖励给发券人的奖励' AFTER `SIGNUP_FULI_MONEY`;

ALTER TABLE `activity_instance_signup` ADD COLUMN `SIGNUP_FULI_SENDER_ID`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '发券人（消费确认后，给此人发奖励）' AFTER `SIGNUP_FULI_AWARD_MONEY`;

ALTER TABLE `activity_instance_signup` ADD COLUMN `SIGNUP_FEE_PRODUCT`  int(11) NULL DEFAULT 0 COMMENT '产品费用' AFTER `SIGNUP_FULI_SENDER_ID`;

ALTER TABLE `qrcode` ADD COLUMN `QRCODE_AGENT_FLAG`  int(1) NULL DEFAULT 0 COMMENT '是否代理标志' AFTER `QRCODE_DESC`;

ALTER TABLE `qrcode` ADD COLUMN `QRCODE_JOIN`  varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' COMMENT '扫描二维码后加入的部落' AFTER `QRCODE_AGENT_FLAG`;

ALTER TABLE `weixin_fuli` ADD COLUMN `GROUP_ID`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '群组邀请码' AFTER `INSTANCE_ID`;

ALTER TABLE `weixin_fuli` MODIFY COLUMN `FULI_MONEY`  int(11) NOT NULL DEFAULT 0 COMMENT '抵扣金额' AFTER `GROUP_ID`;

ALTER TABLE `weixin_fuli` ADD COLUMN `FULI_MONEY_VIP`  int(11) NOT NULL DEFAULT 0 COMMENT '对VIP会员的抵扣金额' AFTER `FULI_MONEY`;

ALTER TABLE `weixin_fuli` ADD COLUMN `AWARD_MONEY`  int(11) NOT NULL DEFAULT 0 COMMENT '消费后奖励给送券者的金额' AFTER `FULI_MONEY_VIP`;

ALTER TABLE `weixin_fuli` ADD COLUMN `AWARD_MONEY_VIP`  int(11) NOT NULL DEFAULT 0 COMMENT '消费后奖励给送券者的金额' AFTER `AWARD_MONEY`;

ALTER TABLE `weixin_fuli` ADD COLUMN `FULI_COUNT`  int(11) NOT NULL DEFAULT 0 COMMENT '福利数量' AFTER `AWARD_MONEY_VIP`;

ALTER TABLE `weixin_fuli` ADD COLUMN `TAKE_COUNT`  int(11) NOT NULL DEFAULT 0 COMMENT '已领数量' AFTER `FULI_DESC`;

ALTER TABLE `weixin_fuli` ADD COLUMN `AWARD_SUM`  int(11) NOT NULL DEFAULT 0 COMMENT '已获得的奖励总额' AFTER `TAKE_COUNT`;

SET FOREIGN_KEY_CHECKS=1;